### PR TITLE
FitFile remove caching of messages

### LINKED ISSUE #59: Do not cache messages in FitParse._messages
When parsing a large FIT file (2MG, 75.000 data messages), the memory consumption is about 90 MB. I have tried to remove `FitParse._messages` and the memory consumption has dropped to 13MB. (And a few percent faster.)

I think the `FitParse._messages` and the property `FitParse.messages` should be removed - caching is the task of the user code.

If you want to keep it, then there should be some parameter like `cache_result` (default `False`).

### PR DESCRIPTION
**Pull request by xmedeko**
Fix #59

### CODE REVIEW

**Comment by xmedeko** [comment]
@dtcooper @pR0Ps Do you agree to break backward compatibility a bit with this PR?

**Comment by pR0Ps** [comment]
I'm ok with breaking backwards compatibility, but only in the cases where the version is bumped to reflect it (ie [semvar](https://semver.org/)).

In this case, I don't think it's worth it by itself. It's not doing anything new or different, it's just removing a feature. If there are other breaking changes happening then this can go in with them, but IMO it's not worth breaking backwards compatibility just for this.

**Comment by xmedeko** [comment]
@pROP This saves a lot of memory. So is necessary when running fitparse on a server. 

I think more BC changes should be mate to fitparse in regards of speed. So, a version bump is necessary.  Better to discuss it somewhere else.

**Comment by dtcooper** [comment]
What about an argument when instantiating `FitFile`'s `__init__` method to turn on/off the message cache?

**Comment by xmedeko** [comment]
@dtcooper Yes, an extra parameter would do the job, too. But IMO the `FitFile` has [too many responsibilities](https://en.wikipedia.org/wiki/Single_responsibility_principle) and should be broken to more classes. See #72 for my proposal.

**Comment by pR0Ps** [comment]
Implemented in 08d49beebba826f606de226acdf1537d47f41e6a

**Pull request closed without merging**
