### PR TITLE
Update library to Python 3

### PR DESCRIPTION
**Pull request by kropp**
I've updated python-fitparse to run on Python 3.
As a part of this update and in order to test generate_profile.py script I also updated FIT SDK to 13.20 released recently.

### CODE REVIEW

**Comment by marctc** [comment]
Seems that @dtcooper is no longer maintaining this project. Perhaps we can merge this PR and others and create a new fork and upload an stable version to PyPI. What do you think?

**Comment by dtcooper** [comment]
That is me. I should probably get on that.

**Comment by marctc** [comment]
I'm glad to see you are alive! thanks @dtcooper

**Comment by kropp** [comment]
@dtcooper Great! If you need any help, just drop me a line.
@marctc Looks like there is no need to fork.

**Comment by marctc** [comment]
@kropp yep!

**Pull request closed without merging**
