### PR TITLE
Create config files for tox and travis-CI

### PR DESCRIPTION
**Pull request by liamjm**
Hey, 

As discussed in https://github.com/dtcooper/python-fitparse/pull/31, here is a start to automated testing environment.

demo of it working:
https://travis-ci.org/liamjm/python-fitparse/branches

Based on my reading of https://docs.travis-ci.com/user/getting-started/ @dtcooper  will need to enable travis-ci for dtcooper/python-fitparse.

Then we can add Markdown like below to the README.md

[Build Status](https://travis-ci.org/dtcooper/python-fitparse)

### CODE REVIEW

**Comment by liamjm** [comment]
@dtcooper: Any time to look at this?

**Comment by dtcooper** [comment]
Hey @liamjm, thanks for the reminder and the PR. I will try to review this week!

**Comment by xmedeko** [comment]
@liamjm I recommend you to squash the 1 or a few meaningful commits so they are more easy to review.

**Comment by huuhuyen** [comment]
Tonyteo

**Comment by huuhuyen** [comment]
Tonyteo_1

**Comment by cwbooth5** [comment]
Between the time you submitted this PR and now, a single unit test started failing as a result of the following commit - https://github.com/dtcooper/python-fitparse/commit/e1e6fd46bf51ad76a62eeb7c66a90f73a314eaf4#commitcomment-31790752

I'm not familiar with the code enough to drill down and find out why the value coming back was so different, but it should probably be investigated first by someone more knowledgeable on the commit.

A suggestion for this PR though: Why not just break it in two components so we can get tox easily runnable by contributors locally without having to rely on travis yet? Maybe just use this PR to get a tox config in place, get the CONTRIBUTING.md in place with instructions blessed by the developer, then make another PR adding in the travis-specific configuration?

I want to help out on this repo because I'm using the code and I think testing can be improved easily. You've done exactly what I was about to do by implementing a basic starting tox configuration here and I really think it should be implemented so we have a starting point. So I guess that would be a +1 from me on this PR.

**Comment by pR0Ps** [comment]
Closing in favour of using GitHub Actions in #119

**Pull request closed without merging**
