### PR TITLE
Big load of changes

### PR DESCRIPTION
**Pull request by pR0Ps**
I've been integrating other people's changes as well as making my own in order to get this library working with recent devices/files/python versions. As a result,  this PR isn't really focused on a specific issue but instead has a random grab-bag of commits.

If you would like to pick and choose which ones to use, feel free, they're mostly divided up into pretty reasonable chunks that could be cherry-picked.

Highlights (see commit messages for details):
 - Python 3 support (~~maybe still works with 2? I didn't test it.~~ ~~Dropped Python 2 support.~~ Python 2.7 still supported) 
 - more tests
 - support for chained fit files
 - updated to the latest version of the SDK (including dev fields)
 - fixed bugs
 - more flexible processing class API (used to implement converting all speeds to km/h)

### CODE REVIEW

**Comment by sanderroosendaal** [comment]
Getting AttributeError: 'module' object has no attribute 'zip_longest' trying to run.

**Comment by pR0Ps** [comment]
@sanderroosendaal 
> Python 3 support (maybe still works with 2? I didn't test it)

Seems it's not working in Python 2, I'll update the PR description.

**Comment by sanderroosendaal** [comment]
Yes, that is Python 2. 
You implemented all the things I need (developer fields support). My site runs on Python 2.7 and is now using the ng branch of python-fitparse.

**Comment by pR0Ps** [comment]
Added Python 2.7 support back in. If anyone finds a file that doesn't parse properly (in 2 or 3), let me know. It works with everything I could find to throw at it using both 2 and 3.

**Comment by dtcooper** [comment]
Carey would you like the maintain this package? I've orphaned it. Got a minute to sync up? I'm at david@dtcooper.com

**Comment by pR0Ps** [comment]
@dtcooper Sent you an email

**Comment by sanderroosendaal** [comment]
In records.py there is a temp.raw_value in line 378 which is not defined. This causes FitFile to choke on one of the attached FIT files when getting the messages
[fitfiles.zip](https://github.com/dtcooper/python-fitparse/files/1031833/fitfiles.zip)

**Comment by pR0Ps** [comment]
@sanderroosendaal whoops, fixed now. I also added one of your files to the repo as a test file. I can remove it if that's not ok with you.

**Comment by dtcooper** [comment]
FYI: Approved for merge @pR0Ps :)

**Comment by dtcooper** [comment]
@pR0Ps All good to kill the `ng` branch when you're done. ;D

**Pull request merged**
