### PR TITLE
warn and fall back to byte encoding, rather than fail, in the case of a mismatched field size

### PR DESCRIPTION
**Pull request by dlenski**
Real-world example in the file `Bicicleta20201025061019.fit` from https://github.com/GoldenCheetah/GoldenCheetah/issues/3645 (device is Coros Pace 2)

It appears to parse fine with this small change.

### CODE REVIEW

**Comment by pR0Ps** [comment]
Looks good to me, would you be able to add that file to the repo and add a test for it? (the uploader gave permission in the linked thread)

**Comment by dlenski** [comment]
Done in 951233d.

Is this repo not set up to run the tests automatically via Travis-CI or GitHub Actions? :thinking:

**Comment by dlenski** [comment]
Here's the form of the offending messages:

```
1803. event [data]
 * event: timer
 * event_group: 0
 * event_type: start
 * timer_trigger: (0,)               # <- uint32, but only 1 byte, not 4 bytes
 * timestamp: 2020-10-25 11:41:39
```

**Comment by pR0Ps** [comment]
Unfortunately no. I've had it in the back of my mind to modernize this repo a bit (drop support for python<3.6, use GitHub Actions to automatically run tests) but haven't gotten around to it.

The change looks good, I just made a small change to capture and test that the warning is being emitted.

**Comment by pR0Ps** [comment]
Thanks!

**Comment by dlenski** [comment]
> Unfortunately no. I've had it in the back of my mind to modernize this repo a bit (drop support for python<3.6, use GitHub Actions to automatically run tests) but haven't gotten around to it.

I recently made some similar upgrades to a couple repos of mine. This one is pretty straightforward:
https://github.com/dlenski/gp-saml-gui/compare/f408593~..3b2bd3d (based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml)

Happy to contribute something similar if you don't get around to it soon.

> The change looks good, I just made a small change to capture and test that the warning is being emitted.

Good idea! :+1:

**Comment by mrumm** [comment]
Any chance you could update the pypi version @dtcooper @pR0Ps ?

**Pull request merged**
