### PR TITLE
Unterminated file fix - See the .csv PR first

### PR DESCRIPTION
**Pull request by scott-phillips-ah**

### CODE REVIEW

**Comment by MeisterP** [comment]
======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/python-fitparse/tests/test.py", line 421
    f.
     ^
SyntaxError: invalid syntax

**Comment by scott-phillips-ah** [comment]
Fixed, that was a typo on my part

**Comment by scott-phillips-ah** [comment]
Fixed, ready for review.

**Comment by pR0Ps** [comment]
Thanks, I'm still looking into the CSV changes but I've merged just this fix to master in 7c0b764

**Pull request closed without merging**
